# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-05-06 21:34
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(help_text='Ingrese el(los) nombre(s) del estudiante (Ej: Juan Pedro)', max_length=100)),
                ('family_name', models.CharField(help_text='Ingrese el(los) apellido(s) del estudiante (Ej: P\xe9rez Gonz\xe1lez)', max_length=100)),
            ],
            options={
                'ordering': ['family_name', 'first_name'],
            },
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Ingrese el nombre del equipo (Ej: ReAL Soluciones)', max_length=200)),
            ],
            options={
                'ordering': ['course', 'name'],
            },
        ),
        migrations.RenameField(
            model_name='course',
            old_name='name',
            new_name='title',
        ),
        migrations.AddField(
            model_name='course',
            name='section',
            field=models.IntegerField(choices=[(1, 1), (2, 2)], default=1),
        ),
        migrations.AddField(
            model_name='course',
            name='semester',
            field=models.CharField(choices=[('Primavera', 'Primavera'), ('Oto\xf1o', 'Oto\xf1o')], default='Primavera', max_length=15),
        ),
        migrations.AddField(
            model_name='course',
            name='year',
            field=models.CharField(default='2019', max_length=4),
        ),
        migrations.AddField(
            model_name='team',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courses.Course'),
        ),
        migrations.AddField(
            model_name='student',
            name='team',
            field=models.ManyToManyField(help_text='Seleccione un equipo para el estudiante', to='courses.Team'),
        ),
        migrations.AlterUniqueTogether(
            name='student',
            unique_together=set([('first_name', 'family_name')]),
        ),
    ]
