# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-04-28 21:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='section',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='course',
            name='semester',
            field=models.CharField(default=0, max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='course',
            name='year',
            field=models.IntegerField(default=0),
        ),
    ]
