# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-04-28 21:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_auto_20190428_2147'),
    ]

    operations = [
        migrations.RenameField(
            model_name='course',
            old_name='name',
            new_name='title',
        ),
        migrations.AlterField(
            model_name='course',
            name='section',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='course',
            name='year',
            field=models.IntegerField(),
        ),
    ]
