# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-04-28 22:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0004_auto_20190428_2209'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='section',
            field=models.CharField(choices=[(1, 1), (2, 2)], default='Primavera', max_length=15),
        ),
        migrations.AlterField(
            model_name='course',
            name='semester',
            field=models.IntegerField(choices=[('Primavera', 'Primavera'), ('Oto\xf1o', 'Oto\xf1o')]),
        ),
    ]
