# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-04-28 22:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0005_auto_20190428_2211'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='section',
            field=models.IntegerField(choices=[(1, 1), (2, 2)]),
        ),
        migrations.AlterField(
            model_name='course',
            name='semester',
            field=models.CharField(choices=[('Primavera', 'Primavera'), ('Oto\xf1o', 'Oto\xf1o')], default='Primavera', max_length=1),
        ),
    ]
