# Generated by Django 2.2.1 on 2019-05-06 20:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0007_auto_20190428_2213'),
    ]

    operations = [
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Ingrese el nombre del equipo (Ej: ReAL Soluciones)', max_length=200)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courses.Course')),
            ],
            options={
                'ordering': ['course', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(help_text='Ingrese el(los) nombre(s) del estudiante (Ej: Juan Pedro)', max_length=100)),
                ('family_name', models.CharField(help_text='Ingrese el(los) apellido(s) del estudiante (Ej: Pérez González)', max_length=100)),
                ('team', models.ManyToManyField(null=True, to='courses.Team')),
            ],
            options={
                'ordering': ['family_name', 'first_name'],
                'unique_together': {('first_name', 'family_name')},
            },
        ),
    ]
