# Generated by Django 2.2.1 on 2019-05-06 20:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0008_student_team'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='team',
            field=models.ManyToManyField(help_text='Seleccione un equipo para el estudiante', to='courses.Team'),
        ),
    ]
