# Generated by Django 2.2.1 on 2019-05-06 23:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Criteria',
            fields=[
                ('name', models.CharField(max_length=200, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Rubric',
            fields=[
                ('name', models.CharField(max_length=200, primary_key=True, serialize=False)),
                ('duration_min', models.PositiveSmallIntegerField()),
                ('duration_max', models.PositiveSmallIntegerField()),
                ('state', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Field',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=200)),
                ('level', models.FloatField()),
                ('criteria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rubrics.Criteria')),
            ],
        ),
        migrations.AddField(
            model_name='criteria',
            name='rubric',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rubrics.Rubric'),
        ),
    ]
